version: '3.8'

services:
  app:
    container_name: app-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    environment:
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: production
    volumes:
      - .:/app
    restart: unless-stopped

  database:
    image: mysql:5.7.33
    container_name: project-penitipan-barang
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    tty: true

volumes:
  db_data:
