version: '3.8'

services:
  app:
    image: penitipan-nest:v0.0.1
    container_name: penitipan-nest
    ports:
      - '8000:8000'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      DOMAIN_URL: ${DOMAIN_URL}
      JWT_SECRET: ${JWT_SECRET}
      USER_EMAIL: ${USER_EMAIL}
      USER_PIN: ${USER_PIN}
      USER_PASS: ${USER_PASS}
    restart: unless-stopped

  database:
    image: mysql:5.7.33
    container_name: mysqlacid
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Jakarta
    ports:
      - '${DB_PORT}:3306'
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    tty: true

volumes:
  db_data:
