version: '3.8'

services:
  app:
    image: penitipan-nest:v0.0.1
    container_name: penitipan-nest
    ports:
      - '8000:8000'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      DOMAIN_URL: ${DOMAIN_URL}
      JWT_SECRET: ${JWT_SECRET}
      USER_EMAIL: ${USER_EMAIL}
      USER_PIN: ${USER_PIN}
      USER_PASS: ${USER_PASS}
    restart: unless-stopped

  database:
    image: postgres:13
    container_name: penitipan-barang
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: '1g'
    restart: always
    tty: true

volumes:
  postgres_data:
    external: true
    name: 2f23434d7c834499d555930fa04ecca726cb07ca2b8ed3202279d5a3ff431b62
