version: '3.8'

services:
  database:
    image: mysql:5.7.33
    container_name: project-penitipang-barang
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    tty: true
