export enum ApiTag {
  USER = 'user',
  AUTH = 'auth',
  MERCHANT = 'merchant',
  SUPPLIER = 'supplier',
  PRODUCT = 'product',
  PRODUCT_UNIT = 'product-unit',
  FINE = 'fine',
  CUSTOMER = 'customer',
  TRANSACTION_IN = 'transaction-in',
  TRANSACTION_IN_HEADER = 'transaction-in-header',
  PAYMENT_METHOD = 'payment-method',
  CUSTOMER_PAYMENT = 'customer-payment',
  AR_PAYMENT = 'ar-payment',
  CASHFLOW = 'cashflow',
  CHARGE = 'charge',
  TRANSACTION_OUT = 'transaction-out',
  REPORT = 'report',
  SPB = 'spb',
  INVOICE = 'invoice',
}
