export enum ApiTag {
  USER = 'user',
  AUTH = 'auth',
  MERCHANT = 'merchant',
  SUPPLIER = 'supplier',
  PRODUCT = 'product',
  PRODUCT_UNIT = 'product-unit',
  FINE = 'fine',
  CUSTOMER = 'customer',
  TRANSACTION_IN = 'transaction-in',
  PAYMENT_METHOD = 'payment-method',
  CUSTOMER_PAYMENT = 'customer-payment',
  AR_PAYMENT = 'ar-payment',
  CASHFLOW = 'cashflow',
}
