export enum DATABASE {
  APP_SETTINGS = 'app_settings',
  AR = 'ar',
  AR_PAYMENT = 'ar_payment',
  CASHFLOWS = 'cashflows',
  CHARGES = 'charges',
  CUSTOMERS = 'customers',
  INVOICES = 'invoices',
  PAYMENT_METHODS = 'payment_methods',
  PRODUCT_UNITS = 'product_units',
  PRODUCTS = 'products',
  SPB = 'spb',
  TRANSACTION_IN_HEADER = 'transaction_in_header',
  TRANSACTION_INS = 'transaction_ins',
  TRANSACTION_OUTS = 'transaction_outs',
  USER_ROLES = 'user_roles',
  USERS = 'users',
}
